PlayerStat update - Postgres fixes (still failing)
Fixed parameter passing to execute - psycopg2 appears to be a bit fussy
about how parameters are passed.

Main query still doesn't work.

psycopg2.DataError: division by zero - appears to be caused by

,round(100*sum(wonAtSD)/sum(sawShowdown)) AS wmsd

Stuck there.