Config: Fix import ordering
L10n change caused:
  File "/home/carlos/Projects/fpdb/fpdboz/pyfpdb/Charset.py", line 25, in <module>
    import Configuration
  File "/home/carlos/Projects/fpdb/fpdboz/pyfpdb/Configuration.py", line 30
    from __future__ import with_statement
SyntaxError: from __future__ imports must occur at the beginning of the file

Who knew?